### Create Order
POST http://localhost:3000/orders
Content-Type: application/json

{
  "id": 1,
  "name": "Example Order",
  "quantity": 5
}

### Get all Orders
GET http://localhost:3000/orders

### Get Order by ID
GET http://localhost:3000/orders/1

### Update Order
PUT http://localhost:3000/orders/1
Content-Type: application/json

{
  "id": 1,
  "name": "Updated Example Order",
  "quantity": 10
}

### Delete Order
DELETE http://localhost:3000/orders/1
