### Create Order
POST http://localhost:6000/orders/order
Content-Type: application/json

{
  "order_amount": "5000",
  "order_date": "2023-04-10",
  "device_id": "1234",
  "delivery_id": "5678",
  "imp_uid": 9101112
}

### Get all Orders
GET http://localhost:6000/orders

### Get Order by ID
GET http://localhost:6000/orders/order/3

### Update Order
PUT http://localhost:6000/orders/order/3
Content-Type: application/json

{
  "order_amount": "20000"
}

### Delete Order
DELETE http://localhost:6000/orders/order/4
